//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Web.WebReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="APWsImplPortBinding", Namespace="http://ws.apservice.viettel.com/")]
    public partial class APWsImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cancelBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback certificateQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback statusQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback receiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelSignatureOperationCompleted;
        
        private System.Threading.SendOrPostCallback batchSignRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback notificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback signatureOperationCompleted;
        
        private System.Threading.SendOrPostCallback connectOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public APWsImplService() {
            this.Url = global::Web.Properties.Settings.Default.Hinet_Web_WebReference_APWsImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cancelBatchCompletedEventHandler cancelBatchCompleted;
        
        /// <remarks/>
        public event certificateQueryCompletedEventHandler certificateQueryCompleted;
        
        /// <remarks/>
        public event statusQueryCompletedEventHandler statusQueryCompleted;
        
        /// <remarks/>
        public event receiptCompletedEventHandler receiptCompleted;
        
        /// <remarks/>
        public event cancelSignatureCompletedEventHandler cancelSignatureCompleted;
        
        /// <remarks/>
        public event batchSignRegistrationCompletedEventHandler batchSignRegistrationCompleted;
        
        /// <remarks/>
        public event notificationCompletedEventHandler notificationCompleted;
        
        /// <remarks/>
        public event signatureCompletedEventHandler signatureCompleted;
        
        /// <remarks/>
        public event connectCompletedEventHandler connectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.apservice.viettel.com/", ResponseNamespace="http://ws.apservice.viettel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public transactionInfo cancelBatch(transactionInfo tranInfo) {
            object[] results = this.Invoke("cancelBatch", new object[] {
                        tranInfo});
            return ((transactionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void cancelBatchAsync(transactionInfo tranInfo) {
            this.cancelBatchAsync(tranInfo, null);
        }
        
        /// <remarks/>
        public void cancelBatchAsync(transactionInfo tranInfo, object userState) {
            if ((this.cancelBatchOperationCompleted == null)) {
                this.cancelBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelBatchOperationCompleted);
            }
            this.InvokeAsync("cancelBatch", new object[] {
                        tranInfo}, this.cancelBatchOperationCompleted, userState);
        }
        
        private void OncancelBatchOperationCompleted(object arg) {
            if ((this.cancelBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelBatchCompleted(this, new cancelBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.apservice.viettel.com/", ResponseNamespace="http://ws.apservice.viettel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public transactionInfo certificateQuery(transactionInfo tranInfo) {
            object[] results = this.Invoke("certificateQuery", new object[] {
                        tranInfo});
            return ((transactionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void certificateQueryAsync(transactionInfo tranInfo) {
            this.certificateQueryAsync(tranInfo, null);
        }
        
        /// <remarks/>
        public void certificateQueryAsync(transactionInfo tranInfo, object userState) {
            if ((this.certificateQueryOperationCompleted == null)) {
                this.certificateQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OncertificateQueryOperationCompleted);
            }
            this.InvokeAsync("certificateQuery", new object[] {
                        tranInfo}, this.certificateQueryOperationCompleted, userState);
        }
        
        private void OncertificateQueryOperationCompleted(object arg) {
            if ((this.certificateQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.certificateQueryCompleted(this, new certificateQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.apservice.viettel.com/", ResponseNamespace="http://ws.apservice.viettel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public transactionInfo statusQuery(transactionInfo tranInfo) {
            object[] results = this.Invoke("statusQuery", new object[] {
                        tranInfo});
            return ((transactionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void statusQueryAsync(transactionInfo tranInfo) {
            this.statusQueryAsync(tranInfo, null);
        }
        
        /// <remarks/>
        public void statusQueryAsync(transactionInfo tranInfo, object userState) {
            if ((this.statusQueryOperationCompleted == null)) {
                this.statusQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstatusQueryOperationCompleted);
            }
            this.InvokeAsync("statusQuery", new object[] {
                        tranInfo}, this.statusQueryOperationCompleted, userState);
        }
        
        private void OnstatusQueryOperationCompleted(object arg) {
            if ((this.statusQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.statusQueryCompleted(this, new statusQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.apservice.viettel.com/", ResponseNamespace="http://ws.apservice.viettel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public transactionInfo receipt(transactionInfo tranInfo) {
            object[] results = this.Invoke("receipt", new object[] {
                        tranInfo});
            return ((transactionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void receiptAsync(transactionInfo tranInfo) {
            this.receiptAsync(tranInfo, null);
        }
        
        /// <remarks/>
        public void receiptAsync(transactionInfo tranInfo, object userState) {
            if ((this.receiptOperationCompleted == null)) {
                this.receiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiptOperationCompleted);
            }
            this.InvokeAsync("receipt", new object[] {
                        tranInfo}, this.receiptOperationCompleted, userState);
        }
        
        private void OnreceiptOperationCompleted(object arg) {
            if ((this.receiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiptCompleted(this, new receiptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.apservice.viettel.com/", ResponseNamespace="http://ws.apservice.viettel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public transactionInfo cancelSignature(transactionInfo tranInfo) {
            object[] results = this.Invoke("cancelSignature", new object[] {
                        tranInfo});
            return ((transactionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void cancelSignatureAsync(transactionInfo tranInfo) {
            this.cancelSignatureAsync(tranInfo, null);
        }
        
        /// <remarks/>
        public void cancelSignatureAsync(transactionInfo tranInfo, object userState) {
            if ((this.cancelSignatureOperationCompleted == null)) {
                this.cancelSignatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelSignatureOperationCompleted);
            }
            this.InvokeAsync("cancelSignature", new object[] {
                        tranInfo}, this.cancelSignatureOperationCompleted, userState);
        }
        
        private void OncancelSignatureOperationCompleted(object arg) {
            if ((this.cancelSignatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelSignatureCompleted(this, new cancelSignatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.apservice.viettel.com/", ResponseNamespace="http://ws.apservice.viettel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public transactionInfo batchSignRegistration(transactionInfo tranInfo) {
            object[] results = this.Invoke("batchSignRegistration", new object[] {
                        tranInfo});
            return ((transactionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void batchSignRegistrationAsync(transactionInfo tranInfo) {
            this.batchSignRegistrationAsync(tranInfo, null);
        }
        
        /// <remarks/>
        public void batchSignRegistrationAsync(transactionInfo tranInfo, object userState) {
            if ((this.batchSignRegistrationOperationCompleted == null)) {
                this.batchSignRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbatchSignRegistrationOperationCompleted);
            }
            this.InvokeAsync("batchSignRegistration", new object[] {
                        tranInfo}, this.batchSignRegistrationOperationCompleted, userState);
        }
        
        private void OnbatchSignRegistrationOperationCompleted(object arg) {
            if ((this.batchSignRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.batchSignRegistrationCompleted(this, new batchSignRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.apservice.viettel.com/", ResponseNamespace="http://ws.apservice.viettel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public transactionInfo notification(transactionInfo tranInfo) {
            object[] results = this.Invoke("notification", new object[] {
                        tranInfo});
            return ((transactionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void notificationAsync(transactionInfo tranInfo) {
            this.notificationAsync(tranInfo, null);
        }
        
        /// <remarks/>
        public void notificationAsync(transactionInfo tranInfo, object userState) {
            if ((this.notificationOperationCompleted == null)) {
                this.notificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnotificationOperationCompleted);
            }
            this.InvokeAsync("notification", new object[] {
                        tranInfo}, this.notificationOperationCompleted, userState);
        }
        
        private void OnnotificationOperationCompleted(object arg) {
            if ((this.notificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.notificationCompleted(this, new notificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.apservice.viettel.com/", ResponseNamespace="http://ws.apservice.viettel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public transactionInfo signature(transactionInfo tranInfo) {
            object[] results = this.Invoke("signature", new object[] {
                        tranInfo});
            return ((transactionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void signatureAsync(transactionInfo tranInfo) {
            this.signatureAsync(tranInfo, null);
        }
        
        /// <remarks/>
        public void signatureAsync(transactionInfo tranInfo, object userState) {
            if ((this.signatureOperationCompleted == null)) {
                this.signatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsignatureOperationCompleted);
            }
            this.InvokeAsync("signature", new object[] {
                        tranInfo}, this.signatureOperationCompleted, userState);
        }
        
        private void OnsignatureOperationCompleted(object arg) {
            if ((this.signatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.signatureCompleted(this, new signatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ws.apservice.viettel.com/", ResponseNamespace="http://ws.apservice.viettel.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public transactionInfo connect(transactionInfo tranInfo) {
            object[] results = this.Invoke("connect", new object[] {
                        tranInfo});
            return ((transactionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void connectAsync(transactionInfo tranInfo) {
            this.connectAsync(tranInfo, null);
        }
        
        /// <remarks/>
        public void connectAsync(transactionInfo tranInfo, object userState) {
            if ((this.connectOperationCompleted == null)) {
                this.connectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconnectOperationCompleted);
            }
            this.InvokeAsync("connect", new object[] {
                        tranInfo}, this.connectOperationCompleted, userState);
        }
        
        private void OnconnectOperationCompleted(object arg) {
            if ((this.connectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.connectCompleted(this, new connectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.apservice.viettel.com/")]
    public partial class transactionInfo {
        
        private string additionDataField;
        
        private string apIdField;
        
        private string apURLField;
        
        private string batchCodeField;
        
        private int batchCountField;
        
        private bool batchCountFieldSpecified;
        
        private string batchExpireDateField;
        
        private string billCodeField;
        
        private int certIdField;
        
        private bool certIdFieldSpecified;
        
        private string certInfoField;
        
        private string[] certListField;
        
        private string certSerialField;
        
        private string dataDisplayField;
        
        private string dataSignField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private int forcePINField;
        
        private bool forcePINFieldSpecified;
        
        private int isBatchSigningSupportedField;
        
        private bool isBatchSigningSupportedFieldSpecified;
        
        private int isSHA2SupportedField;
        
        private bool isSHA2SupportedFieldSpecified;
        
        private string keyHashField;
        
        private string keyValueField;
        
        private string macField;
        
        private string manufacturerField;
        
        private string msgModeField;
        
        private string msisdnField;
        
        private string mssFormatField;
        
        private string msspIdField;
        
        private string orgErrCodeField;
        
        private string orgErrDescField;
        
        private string orgRequestApIdField;
        
        private long orgRequestIdField;
        
        private bool orgRequestIdFieldSpecified;
        
        private string processCodeField;
        
        private string reqDateField;
        
        private long requestIdField;
        
        private bool requestIdFieldSpecified;
        
        private string resDateField;
        
        private int runImmField;
        
        private bool runImmFieldSpecified;
        
        private int sigTypeField;
        
        private bool sigTypeFieldSpecified;
        
        private string signatureField;
        
        private long timeoutField;
        
        private bool timeoutFieldSpecified;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string additionData {
            get {
                return this.additionDataField;
            }
            set {
                this.additionDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apId {
            get {
                return this.apIdField;
            }
            set {
                this.apIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apURL {
            get {
                return this.apURLField;
            }
            set {
                this.apURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batchCode {
            get {
                return this.batchCodeField;
            }
            set {
                this.batchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int batchCount {
            get {
                return this.batchCountField;
            }
            set {
                this.batchCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool batchCountSpecified {
            get {
                return this.batchCountFieldSpecified;
            }
            set {
                this.batchCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string batchExpireDate {
            get {
                return this.batchExpireDateField;
            }
            set {
                this.batchExpireDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string billCode {
            get {
                return this.billCodeField;
            }
            set {
                this.billCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int certId {
            get {
                return this.certIdField;
            }
            set {
                this.certIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certIdSpecified {
            get {
                return this.certIdFieldSpecified;
            }
            set {
                this.certIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certInfo {
            get {
                return this.certInfoField;
            }
            set {
                this.certInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("certList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] certList {
            get {
                return this.certListField;
            }
            set {
                this.certListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certSerial {
            get {
                return this.certSerialField;
            }
            set {
                this.certSerialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataDisplay {
            get {
                return this.dataDisplayField;
            }
            set {
                this.dataDisplayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataSign {
            get {
                return this.dataSignField;
            }
            set {
                this.dataSignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int forcePIN {
            get {
                return this.forcePINField;
            }
            set {
                this.forcePINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forcePINSpecified {
            get {
                return this.forcePINFieldSpecified;
            }
            set {
                this.forcePINFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isBatchSigningSupported {
            get {
                return this.isBatchSigningSupportedField;
            }
            set {
                this.isBatchSigningSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isBatchSigningSupportedSpecified {
            get {
                return this.isBatchSigningSupportedFieldSpecified;
            }
            set {
                this.isBatchSigningSupportedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isSHA2Supported {
            get {
                return this.isSHA2SupportedField;
            }
            set {
                this.isSHA2SupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSHA2SupportedSpecified {
            get {
                return this.isSHA2SupportedFieldSpecified;
            }
            set {
                this.isSHA2SupportedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyHash {
            get {
                return this.keyHashField;
            }
            set {
                this.keyHashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyValue {
            get {
                return this.keyValueField;
            }
            set {
                this.keyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mac {
            get {
                return this.macField;
            }
            set {
                this.macField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgMode {
            get {
                return this.msgModeField;
            }
            set {
                this.msgModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mssFormat {
            get {
                return this.mssFormatField;
            }
            set {
                this.mssFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msspId {
            get {
                return this.msspIdField;
            }
            set {
                this.msspIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgErrCode {
            get {
                return this.orgErrCodeField;
            }
            set {
                this.orgErrCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgErrDesc {
            get {
                return this.orgErrDescField;
            }
            set {
                this.orgErrDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orgRequestApId {
            get {
                return this.orgRequestApIdField;
            }
            set {
                this.orgRequestApIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long orgRequestId {
            get {
                return this.orgRequestIdField;
            }
            set {
                this.orgRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orgRequestIdSpecified {
            get {
                return this.orgRequestIdFieldSpecified;
            }
            set {
                this.orgRequestIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string processCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reqDate {
            get {
                return this.reqDateField;
            }
            set {
                this.reqDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestIdSpecified {
            get {
                return this.requestIdFieldSpecified;
            }
            set {
                this.requestIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resDate {
            get {
                return this.resDateField;
            }
            set {
                this.resDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int runImm {
            get {
                return this.runImmField;
            }
            set {
                this.runImmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool runImmSpecified {
            get {
                return this.runImmFieldSpecified;
            }
            set {
                this.runImmFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sigType {
            get {
                return this.sigTypeField;
            }
            set {
                this.sigTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sigTypeSpecified {
            get {
                return this.sigTypeFieldSpecified;
            }
            set {
                this.sigTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeoutSpecified {
            get {
                return this.timeoutFieldSpecified;
            }
            set {
                this.timeoutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void cancelBatchCompletedEventHandler(object sender, cancelBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public transactionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transactionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void certificateQueryCompletedEventHandler(object sender, certificateQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class certificateQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal certificateQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public transactionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transactionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void statusQueryCompletedEventHandler(object sender, statusQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class statusQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal statusQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public transactionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transactionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void receiptCompletedEventHandler(object sender, receiptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receiptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public transactionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transactionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void cancelSignatureCompletedEventHandler(object sender, cancelSignatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelSignatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelSignatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public transactionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transactionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void batchSignRegistrationCompletedEventHandler(object sender, batchSignRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class batchSignRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal batchSignRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public transactionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transactionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void notificationCompletedEventHandler(object sender, notificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class notificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal notificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public transactionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transactionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void signatureCompletedEventHandler(object sender, signatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class signatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal signatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public transactionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transactionInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void connectCompletedEventHandler(object sender, connectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class connectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal connectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public transactionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transactionInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591